Fix panics when using iif or oif with ip rule
little-dude/netlink pull request #280
Opened 2022-07-27 13:04 UTC by dxfgg17

Copying string s (which size is `n`) in buffer of size `n+1` always panics because rust expect two slices of same length.

Since buffer has been initialized with 0, no need to add a second instruction like : `buffer[5] = 0;`.

2022-08-11 00:14 UTC, cathay4t submitted a review, later dismissed

2022-08-11 00:20 UTC, cathay4t requested changes
CI found this compile warning at https://github.com/little-dude/netlink/runs/7778198529?check_suite_focus=true#step:13:9

```
warning: variable does not need to be mutable
   --> netlink-packet-route/src/rtnl/rule/nlas/mod.rs:119:26
    |
119 |     fn emit_value(&self, mut buffer: &mut [u[8](https://github.com/little-dude/netlink/runs/7778198529?check_suite_focus=true#step:13:9)]) {
    |                          ----^^^^^^
    |                          |
    |                          help: remove this `mut`
    |
    = note: `#[warn(unused_mut)]` on by default
```

2022-08-11 14:23 UTC, dxfgg17 commented
> compile

Sorry for the mistake and thank you for your review. I fixed the issue :)

2022-08-16 00:26 UTC, cathay4t approved these changes

2022-08-16 00:26 UTC, merged

2022-08-16 00:26 UTC, cathay4t commented
Merged. Thanks!